<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE>
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>hl7</string>
    </array>
    <key>name</key>
    <string>HL7 Vivid</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^(ABS|ACC|ADD|ADJ|AFF|AIG|AIL|AIP|AIS|AL1|APR|ARQ|ARV|AUT|BHS|BLC|BLG|BPO|BPX|BTS|BTX|BUI|CDM|CDO|CER|CM0|CM1|CM2|CNS|CON|CSP|CSR|CSS|CTD|CTI|DB1|DG1|DMI|DON|DRG|DSC|DSP|ECD|ECR|EDU|EQP|EQU|ERR|EVN|FAC|FHS|FT1|FTS|GOL|GP1|GP2|GT1|H\d\d|IAM|IAR|IIM|ILT|IN1|IN2|IN3|INV|IPC|IPR|ISD|ITM|IVC|IVT|LAN|LCC|LCH|LDP|LOC|LRL|MFA|MFE|MFI|MRG|MSA|MSH|NCK|NDS|NK1|NPU|NSC|NST|NTE|OBR|OBX|ODS|ODT|OM1|OM2|OM3|OM4|OM5|OM6|OM7|OMC|OMP|ORC|ORG|ORP|OVR|PAC|PCE|PCR|PD1|PDA|PDC|PEO|PES|PID|PKG|PM1|PMT|PR1|PRA|PRB|PRC|PRD|PRT|PSG|PSH|PSL|PSS|PTH|PV1|PV2|PYE|QAK|QID|QPD|QRD|QRF|QRI|RCP|RDF|RDT|REL|RF1|RFI|RGS|RMI|ROL|RQ1|RQD|RRD|RXA|RXC|RXD|RXE|RXG|RXO|RXR|RXV|SAC|SCD|SCH|SCP|SDD|SFT|SGH|SGT|SHP|SID|SLT|SPM|STF|STZ|TCC|TCD|TQ1|TQ2|TXA|UAC|UB1|UB2|URD|URS|VAR|VND|ZL7|Z\d\d)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(ABS|ACC|ADD|ADJ|AFF|AIG|AIL|AIP|AIS|AL1|APR|ARQ|ARV|AUT|BHS|BLC|BLG|BPO|BPX|BTS|BTX|BUI|CDM|CDO|CER|CM0|CM1|CM2|CNS|CON|CSP|CSR|CSS|CTD|CTI|DB1|DG1|DMI|DON|DRG|DSC|DSP|ECD|ECR|EDU|EQP|EQU|ERR|EVN|FAC|FHS|FT1|FTS|GOL|GP1|GP2|GT1|H\d\d|IAM|IAR|IIM|ILT|IN1|IN2|IN3|INV|IPC|IPR|ISD|ITM|IVC|IVT|LAN|LCC|LCH|LDP|LOC|LRL|MFA|MFE|MFI|MRG|MSA|MSH|NCK|NDS|NK1|NPU|NSC|NST|NTE|OBR|OBX|ODS|ODT|OM1|OM2|OM3|OM4|OM5|OM6|OM7|OMC|OMP|ORC|ORG|ORP|OVR|PAC|PCE|PCR|PD1|PDA|PDC|PEO|PES|PID|PKG|PM1|PMT|PR1|PRA|PRB|PRC|PRD|PRT|PSG|PSH|PSL|PSS|PTH|PV1|PV2|PYE|QAK|QID|QPD|QRD|QRF|QRI|RCP|RDF|RDT|REL|RF1|RFI|RGS|RMI|ROL|RQ1|RQD|RRD|RXA|RXC|RXD|RXE|RXG|RXO|RXR|RXV|SAC|SCD|SCH|SCP|SDD|SFT|SGH|SGT|SHP|SID|SLT|SPM|STF|STZ|TCC|TCD|TQ1|TQ2|TXA|UAC|UB1|UB2|URD|URS|VAR|VND|ZL7|Z\d\d)(\|)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(\^|&|~)</string>
            <key>name</key>
            <string>string.other.hl7</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(\|)(ACK|ADR|ADT|BAR|BPS|BRP|BRT|BTS|CCF|CCI|CCM|CCQ|CCR|CCU|CQU|CRM|CSU|DBC|DEL|DEO|DER|DFT|DOC|DPR|DRC|DRG|DSR|EAC|EAN|EAR|EDR|EHC|EQQ|ERP|ESR|ESU|INR|INU|LSU|MDM|MFK|MFN|MFQ|MFR|NMD|NMQ|NMR|OMB|OMD|OMG|OMI|OML|OMN|OMP|OMQ|OMS|OPL|OPR|OPU|ORA|ORB|ORD|ORF|ORG|ORI|ORL|ORM|ORN|ORP|ORR|ORS|ORU|ORX|OSM|OSQ|OSR|OSU|OUL|PEX|PGL|PMU|PPG|PPP|PPR|QBP|QCK|QCN|QRY|QSB|QVR|RAR|RAS|RCI|RCL|RDE|RDR|RDS|RDY|REF|RER|RGR|RGV|ROR|RPA|RPI|RPL|RPR|RQA|RQC|RQI|RQP|RQQ|RRA|RRD|RRE|RRG|RRI|RSP|RTB|SDR|SIU|SLR|SPQ|SQM|SQR|SRM|SRR|SSR|SSU|STC|TBR|TCU|UDM|VQQ|VXQ|VXR|VXU|VXX)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.block</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>markup.inserted</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>name</key>
            <string>comment.block</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>markup.inserted</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(.*?)</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>\|</string>
            <key>name</key>
            <string>comment.block</string>
        </dict>
    </array>
</dict>
</plist>