# Handles the definition of the HL7 events
class hl7Event(object):
	def __init__(self, code, description):
		self.code = code
		self.description = description

	# Gets a event object based on his code. If no object is found in the eventList with the following code None is returned.
	def getEventByCode(self, code, eventList):
		for listItem in eventList:
			if (listItem.code == code):
				return listItem
		return None

	# Loads the entire event list
	def loadEventList(self):
		hl7EventList = []

		hl7EventList.append(hl7Event("ACK", "General acknowledgment message"))
		hl7EventList.append(hl7Event("ADR_A19", "Patient query"))
		hl7EventList.append(hl7Event("ADT_A01", "Admit/visit notification"))
		hl7EventList.append(hl7Event("ADT_A02", "Transfer a patient"))
		hl7EventList.append(hl7Event("ADT_A03", "Discharge/end visit"))
		hl7EventList.append(hl7Event("ADT_A04", "Register a patient"))
		hl7EventList.append(hl7Event("ADT_A05", "Pre-admit a patient"))
		hl7EventList.append(hl7Event("ADT_A06", "Change an outpatient to an inpatient"))
		hl7EventList.append(hl7Event("ADT_A07", "Change an inpatient to an outpatient"))
		hl7EventList.append(hl7Event("ADT_A08", "Update patient information"))
		hl7EventList.append(hl7Event("ADT_A09", "Patient departing - tracking"))
		hl7EventList.append(hl7Event("ADT_A10", "Patient arriving - tracking"))
		hl7EventList.append(hl7Event("ADT_A11", "Cancel admit/visit notification"))
		hl7EventList.append(hl7Event("ADT_A12", "Cancel transfer"))
		hl7EventList.append(hl7Event("ADT_A13", "Cancel discharge/end visit"))
		hl7EventList.append(hl7Event("ADT_A14", "Pending admit"))
		hl7EventList.append(hl7Event("ADT_A15", "Pending transfer"))
		hl7EventList.append(hl7Event("ADT_A16", "Pending discharge"))
		hl7EventList.append(hl7Event("ADT_A17", "Swap patients"))
		hl7EventList.append(hl7Event("ADT_A18", "Merge patient information"))
		hl7EventList.append(hl7Event("ADT_A20", "Bed status update"))
		hl7EventList.append(hl7Event("ADT_A21", "Patient goes on a \"leave of absence\""))
		hl7EventList.append(hl7Event("ADT_A22", "Patient returns from a \"leave of absence\""))
		hl7EventList.append(hl7Event("ADT_A23", "Delete a patient record"))
		hl7EventList.append(hl7Event("ADT_A24", "Link patient information"))
		hl7EventList.append(hl7Event("ADT_A25", "Cancel pending discharge"))
		hl7EventList.append(hl7Event("ADT_A26", "Cancel pending transfer"))
		hl7EventList.append(hl7Event("ADT_A27", "Cancel pending admit"))
		hl7EventList.append(hl7Event("ADT_A28", "Add person information"))
		hl7EventList.append(hl7Event("ADT_A29", "Delete person information"))
		hl7EventList.append(hl7Event("ADT_A30", "Merge person information"))
		hl7EventList.append(hl7Event("ADT_A31", "Update person information"))
		hl7EventList.append(hl7Event("ADT_A32", "Cancel patient arriving - tracking"))
		hl7EventList.append(hl7Event("ADT_A33", "Cancel patient departing - tracking"))
		hl7EventList.append(hl7Event("ADT_A34", "Merge patient information - patient id only"))
		hl7EventList.append(hl7Event("ADT_A35", "Merge patient information - account number only"))
		hl7EventList.append(hl7Event("ADT_A36", "Merge patient information - patient id and account number"))
		hl7EventList.append(hl7Event("ADT_A37", "Unlink patient information"))
		hl7EventList.append(hl7Event("ADT_A38", "Cancel pre-admit"))
		hl7EventList.append(hl7Event("ADT_A39", "Merge person - patient id"))
		hl7EventList.append(hl7Event("ADT_A40", "Merge patient - patient identifier list"))
		hl7EventList.append(hl7Event("ADT_A41", "Merge account - patient account number"))
		hl7EventList.append(hl7Event("ADT_A42", "Merge visit - visit number"))
		hl7EventList.append(hl7Event("ADT_A43", "Move patient information - patient identifier list"))
		hl7EventList.append(hl7Event("ADT_A44", "Move account information - patient account number"))
		hl7EventList.append(hl7Event("ADT_A45", "Move visit information - visit number"))
		hl7EventList.append(hl7Event("ADT_A46", "Change patient id (for backward compatibility only)"))
		hl7EventList.append(hl7Event("ADT_A47", "Change patient identifier list"))
		hl7EventList.append(hl7Event("ADT_A48", "Change alternate patient id"))
		hl7EventList.append(hl7Event("ADT_A49", "Change patient account number"))
		hl7EventList.append(hl7Event("ADT_A50", "Change visit number"))
		hl7EventList.append(hl7Event("ADT_A51", "Change alternate visit id"))
		hl7EventList.append(hl7Event("ADT_A52", "Cancel leave of absence for a patient"))
		hl7EventList.append(hl7Event("ADT_A53", "Cancel patient returns from a leave of absence"))
		hl7EventList.append(hl7Event("ADT_A54", "Change attending doctor"))
		hl7EventList.append(hl7Event("ADT_A55", "Cancel change attending doctor"))
		hl7EventList.append(hl7Event("ADT_A60", "Update allergy information"))
		hl7EventList.append(hl7Event("ADT_A61", "Change consulting doctor"))
		hl7EventList.append(hl7Event("ADT_A62", "Cancel change consulting doctor"))
		hl7EventList.append(hl7Event("BAR_P01", "Add patient accounts"))
		hl7EventList.append(hl7Event("BAR_P02", "Purge patient accounts"))
		hl7EventList.append(hl7Event("BAR_P05", "Update account"))
		hl7EventList.append(hl7Event("BAR_P06", "End account"))
		hl7EventList.append(hl7Event("BAR_P10", "Transmit ambulatory payment classification(apc)"))
		hl7EventList.append(hl7Event("BAR_P12", "Update diagnose/procedure"))
		hl7EventList.append(hl7Event("BPS_O29", "Blood product dispense status message"))
		hl7EventList.append(hl7Event("BRP_O30", "Blood product dispense status acknowledgment"))
		hl7EventList.append(hl7Event("BRT_O32", "Blood product transfusion/disposition acknowledgment"))
		hl7EventList.append(hl7Event("BTS_O31", "Blood product transfusion/disposition message"))
		hl7EventList.append(hl7Event("CRM_C01", "Register a patient on a clinical trial"))
		hl7EventList.append(hl7Event("CSU_C09", "Automated time intervals for reporting, like monthly"))
		hl7EventList.append(hl7Event("DFT_P03", "Post detail financial transaction"))
		hl7EventList.append(hl7Event("DFT_P11", "Detail financial transactions"))
		hl7EventList.append(hl7Event("DOC_T12", "Document response"))
		hl7EventList.append(hl7Event("DSR_Q01", "Display response message"))
		hl7EventList.append(hl7Event("DSR_Q03", "Deferred response to a query"))
		hl7EventList.append(hl7Event("EAC_U07", "Automated equipment command"))
		hl7EventList.append(hl7Event("EAN_U09", "Automated equipment notification"))
		hl7EventList.append(hl7Event("EAR_U08", "Automated equipment response"))
		hl7EventList.append(hl7Event("EDR_R07", "Enhanced display response"))
		hl7EventList.append(hl7Event("EQQ_Q04", "Embedded query language query"))
		hl7EventList.append(hl7Event("ERP_R09", "Event replay response"))
		hl7EventList.append(hl7Event("ESR_U02", "Automated equipment status request"))
		hl7EventList.append(hl7Event("ESU_U01", "Automated equipment status update"))
		hl7EventList.append(hl7Event("INR_U06", "Automated equipment inventory request"))
		hl7EventList.append(hl7Event("INU_U05", "Automated equipment inventory update"))
		hl7EventList.append(hl7Event("LSU_U12", "Automated equipment log/service update"))
		hl7EventList.append(hl7Event("MDM_T01", "Original document notification"))
		hl7EventList.append(hl7Event("MDM_T02", "Original document notification and content"))
		hl7EventList.append(hl7Event("MFK_M01", "Master file application acknowledgment"))
		hl7EventList.append(hl7Event("MFN_M02", "Master file - staff practitioner"))
		hl7EventList.append(hl7Event("MFN_M04", "Master files charge description"))
		hl7EventList.append(hl7Event("MFN_M05", "Patient location master file"))
		hl7EventList.append(hl7Event("MFN_M06", "Clinical study with phases and schedules master file"))
		hl7EventList.append(hl7Event("MFN_M07", "Clinical study without phases but with schedules master file"))
		hl7EventList.append(hl7Event("MFN_M08", "Test/observation (numeric) master file"))
		hl7EventList.append(hl7Event("MFN_M09", "Test/observation (categorical) master file"))
		hl7EventList.append(hl7Event("MFN_M10", "Test/observation batteries master file"))
		hl7EventList.append(hl7Event("MFN_M11", "Test/calculated observations master file"))
		hl7EventList.append(hl7Event("MFN_M12", "Master file notification message"))
		hl7EventList.append(hl7Event("MFN_M13", "Master files notification - general"))
		hl7EventList.append(hl7Event("MFN_M15", "Inventory item master file message"))
		hl7EventList.append(hl7Event("MFQ_M01", "Query for master file record"))
		hl7EventList.append(hl7Event("MFR_M04", "Charge description master file message"))
		hl7EventList.append(hl7Event("MFR_M05", "Patient location master file message"))
		hl7EventList.append(hl7Event("MFR_M06", "Clinical trials master file message"))
		hl7EventList.append(hl7Event("MFR_M07", "Clinical trials master file message"))
		hl7EventList.append(hl7Event("NMD_N02", "Application management data message"))
		hl7EventList.append(hl7Event("NMQ_N01", "Application management query message"))
		hl7EventList.append(hl7Event("NMR_N01", "Application management response"))
		hl7EventList.append(hl7Event("OMB_O27", "Usage notes for transfusion service message"))
		hl7EventList.append(hl7Event("OMD_O03", "Diet order"))
		hl7EventList.append(hl7Event("OMG_O19", "General clinical order"))
		hl7EventList.append(hl7Event("OMI_O23", "Imaging Order Message"))
		hl7EventList.append(hl7Event("OML_O21", "Laboratory order"))
		hl7EventList.append(hl7Event("OML_O33", "Laboratory order message"))
		hl7EventList.append(hl7Event("OML_O35", "Laboratory order message"))
		hl7EventList.append(hl7Event("OMN_O07", "Non-stock requisition order"))
		hl7EventList.append(hl7Event("OMP_O09", "Pharmacy/treatment order"))
		hl7EventList.append(hl7Event("OMS_O05", "Stock requisition order"))
		hl7EventList.append(hl7Event("ORB_O28", "Blood product order acknowledgment"))
		hl7EventList.append(hl7Event("ORD_O04", "Diet order acknowledgement"))
		hl7EventList.append(hl7Event("ORF_R04", "Response to query\", \" transmission of requested observation"))
		hl7EventList.append(hl7Event("ORG_O20", "General clinical order response"))
		hl7EventList.append(hl7Event("ORI_O24", "Imaging order response message to any OMI message"))
		hl7EventList.append(hl7Event("ORL_O22", "Response message to oml"))
		hl7EventList.append(hl7Event("ORL_O36", "Laboratory acknowledgment message"))
		hl7EventList.append(hl7Event("ORM_O01", "Order message"))
		hl7EventList.append(hl7Event("ORN_O08", "Non-stock requisition acknowledgement"))
		hl7EventList.append(hl7Event("ORP_O10", "Pharmacy/treatment order acknowledgement"))
		hl7EventList.append(hl7Event("ORR_O02", "Order response"))
		hl7EventList.append(hl7Event("ORS_O06", "Stock requisition acknowledgement"))
		hl7EventList.append(hl7Event("ORU", "Unsolicited transmission of an observation message"))
		hl7EventList.append(hl7Event("ORU_R01", "Unsolicited transmission of an observation message"))
		hl7EventList.append(hl7Event("ORU_R30", "Unsolicited transmission of an observation message"))
		hl7EventList.append(hl7Event("OSQ_Q06", "Query for order status"))
		hl7EventList.append(hl7Event("OSR_Q06", "Query response for order status"))
		hl7EventList.append(hl7Event("OUL_R21", "Unsolicited laboratory observation"))
		hl7EventList.append(hl7Event("OUL_R22", "Unsolicited laboratory observation message"))
		hl7EventList.append(hl7Event("OUL_R23", "Unsolicited laboratory observation message"))
		hl7EventList.append(hl7Event("OUL_R24", "Unsolicited laboratory observation message"))
		hl7EventList.append(hl7Event("PEX_P07", "Unsolicited initial individual product experience report"))
		hl7EventList.append(hl7Event("PMU_B01", "Add personnel record"))
		hl7EventList.append(hl7Event("PMU_B03", "Delete personnel record"))
		hl7EventList.append(hl7Event("PMU_B04", "Active practicing person"))
		hl7EventList.append(hl7Event("PMU_B07", "Add personnel record"))
		hl7EventList.append(hl7Event("PMU_B08", "Add personnel record"))
		hl7EventList.append(hl7Event("QBP_K13", "Query by parameter"))
		hl7EventList.append(hl7Event("QBP_Q11", "Query by parameter"))
		hl7EventList.append(hl7Event("QBP_Q13", "Query by parameter"))
		hl7EventList.append(hl7Event("QBP_Q21", "Query by parameter"))
		hl7EventList.append(hl7Event("QBP_Q22", "Query - Find Candidates"))
		hl7EventList.append(hl7Event("QBP_Z73", "Query by parameter"))
		hl7EventList.append(hl7Event("QCK_Q02", "Deferred query"))
		hl7EventList.append(hl7Event("QCN_J01", "Cancel query/acknowledge message"))
		hl7EventList.append(hl7Event("QRY", "Query"))
		hl7EventList.append(hl7Event("QRY_A19", "Patient query"))
		hl7EventList.append(hl7Event("QRY_PC4", "Problem query"))
		hl7EventList.append(hl7Event("QRY_Q01", "Query sent for immediate response"))
		hl7EventList.append(hl7Event("QRY_Q02", "Query sent for deferred response"))
		hl7EventList.append(hl7Event("QRY_R02", "Query for results of observation"))
		hl7EventList.append(hl7Event("QSB_Q16", "Create subscription"))
		hl7EventList.append(hl7Event("RAR_RAR", "Pharmacy/treatment administration information"))
		hl7EventList.append(hl7Event("RAS_O17", "Pharmacy/treatment administration"))
		hl7EventList.append(hl7Event("RCI_I05", "Return clinical information"))
		hl7EventList.append(hl7Event("RCL_I06", "Return clinical information"))
		hl7EventList.append(hl7Event("RDE_O11", "Pharmacy/treatment encoded order"))
		hl7EventList.append(hl7Event("RDR_RDR", "Pharmacy/treatment dispense information"))
		hl7EventList.append(hl7Event("RDS_O13", "Pharmacy/treatment dispense"))
		hl7EventList.append(hl7Event("RDY_K15", "Display based response"))
		hl7EventList.append(hl7Event("REF_I12", "Patient referral"))
		hl7EventList.append(hl7Event("RER_RER", "Pharmacy/treatment encoded order information"))
		hl7EventList.append(hl7Event("RGR_RGR", "Pharmacy/treatment dose information"))
		hl7EventList.append(hl7Event("RGV_O15", "Pharmacy/treatment give"))
		hl7EventList.append(hl7Event("ROR_ROR", "Pharmacy prescription order query response"))
		hl7EventList.append(hl7Event("RPA_I08", "Return patient authorization"))
		hl7EventList.append(hl7Event("RPI_I01", "Return patient information"))
		hl7EventList.append(hl7Event("RPI_I04", "Return patient information"))
		hl7EventList.append(hl7Event("RPL_I02", "Return patient display list"))
		hl7EventList.append(hl7Event("RPR_I03", "Return patient list"))
		hl7EventList.append(hl7Event("RQA_I08", "Request for treatment authorization information"))
		hl7EventList.append(hl7Event("RQC_I05", "Request for patient clinical information"))
		hl7EventList.append(hl7Event("RQI_I01", "Request for insurance information"))
		hl7EventList.append(hl7Event("RQP_I04", "Request patient demographics"))
		hl7EventList.append(hl7Event("RQQ_Q09", "Event replay query"))
		hl7EventList.append(hl7Event("RRA_O18", "Pharmacy/treatment administration acknowledgement"))
		hl7EventList.append(hl7Event("RRD_O14", "Pharmacy/treatment dispense acknowledgement"))
		hl7EventList.append(hl7Event("RRE_O12", "Pharmacy/treatment encoded order acknowledgement"))
		hl7EventList.append(hl7Event("RRG_O16", "Pharmacy/treatment give acknowledgement"))
		hl7EventList.append(hl7Event("RRI_I12", "Return referral information"))
		hl7EventList.append(hl7Event("RSP_K11", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_K21", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_K22", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_K23", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_K25", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_K31", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_Q11", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_Z82", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_Z86", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_Z88", "Segment pattern response"))
		hl7EventList.append(hl7Event("RSP_Z90", "Segment pattern response"))
		hl7EventList.append(hl7Event("RTB_K13", "Tabular response"))
		hl7EventList.append(hl7Event("RTB_Z74", "Tabular response"))
		hl7EventList.append(hl7Event("SIU_S12", "Notification of new appointment booking"))
		hl7EventList.append(hl7Event("SIU_S13", "Notification of Appointment Rescheduling"))
		hl7EventList.append(hl7Event("SIU_S14", "Notification of Appointment Modification"))
		hl7EventList.append(hl7Event("SIU_S15", "Notification of Appointment Cancellation"))
		hl7EventList.append(hl7Event("SIU_S16", "Notification of Appointment Discontinuation"))
		hl7EventList.append(hl7Event("SIU_S17", "Notification of Appointment Deletion"))
		hl7EventList.append(hl7Event("SIU_S18", "Notification of Addition of Service/Resource on Appointment"))
		hl7EventList.append(hl7Event("SIU_S19", "Notification of Modification of Service/Resource on Appointment"))
		hl7EventList.append(hl7Event("SIU_S20", "Notification of Cancellation of Service/Resource on Appointment"))
		hl7EventList.append(hl7Event("SIU_S21", "Notification of Discontinuation of Service/Resource on Appointment"))
		hl7EventList.append(hl7Event("SIU_S22", "Notification of Deletion of Service/Resource on Appointment"))
		hl7EventList.append(hl7Event("SIU_S23", "Notification of Blocked Schedule Time Slot(S)"))
		hl7EventList.append(hl7Event("SIU_S24", "Notification of Opened (un-blocked) Schedule Time Slot(s)"))
		hl7EventList.append(hl7Event("SIU_S26", "Notification That Patient Did Not Show Up for Scheduled Appointment"))
		hl7EventList.append(hl7Event("SPQ_Q08", "Stored procedure request"))
		hl7EventList.append(hl7Event("SQM_S25", "Schedule query message and response"))
		hl7EventList.append(hl7Event("SQR_S25", "Schedule query message and response"))
		hl7EventList.append(hl7Event("SRM_S01", "Request new appointment booking"))
		hl7EventList.append(hl7Event("SRR_S01", "Scheduled request response"))
		hl7EventList.append(hl7Event("SSR_U04", "Specimen status request"))
		hl7EventList.append(hl7Event("SSU_U03", "Specimen status update"))
		hl7EventList.append(hl7Event("TBR_R08", "Tabular data response"))
		hl7EventList.append(hl7Event("TCU_U10", "Automated equipment test code settings update"))
		hl7EventList.append(hl7Event("UDM_Q05", "Unsolicited display update message"))
		hl7EventList.append(hl7Event("VQQ_Q07", "Virtual table query"))
		hl7EventList.append(hl7Event("VXQ_V01", "Query for vaccination record"))
		hl7EventList.append(hl7Event("VXR_V03", "Vaccination record response"))
		hl7EventList.append(hl7Event("VXU_V04", "Unsolicited vaccination record update"))
		hl7EventList.append(hl7Event("VXX_V02", "Response to vaccination query"))

		return hl7EventList
